apps/blog/urls.py
# apps/blog/urls.py

# Django modules
from django.urls import path

# My modules
from blog import views

# Namespace
app_name = 'blog'

urlpatterns = [
	path('', views.home_view, name='home'),
	path('post/create/', views.post_create_view, name='create'),
	path('post/edit/<int:pk>/', views.post_edit_view, name='edit'),
	path('post/delete/<int:pk>/', views.post_delete_view, name='delete'),
	path('post/tags/<slug:tag>/', views.home_view, name='posts_by_tag'), 
	path('post/<slug:slug>/', views.post_detail_view, name='detail'), 
	path('about/', views.about_view, name='about'), 
]

config/urls.py
# config/urls.py

# Django modules
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    # blog
    path('', include('blog.urls', namespace='blog')),
    # django-allauth
    path('accounts/', include('allauth.urls')),
    # admin
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
# apps/blog/models.py

# Django modules
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User 

# Third party modules
from taggit.managers import TaggableManager
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill

# Create your models here.


class Post(models.Model):
    title = models.CharField(default='', max_length=255)
    slug = models.SlugField(
            default='', 
            max_length=255, 
            blank=True,
            help_text='Live it blank. It will be automatically fill in once post title is added.')
    body = models.TextField(default='', blank=True)
    author = models.ForeignKey(
            User, 
            on_delete=models.CASCADE,
            blank=True,
            null=True)
    # Image
    image = models.ImageField(
        default='',
        blank=True,
        upload_to='images')
    # Image thumbnail
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[ResizeToFill(700, 150)],
        format='JPEG',
        options={'quality': 60})
    date = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True)

    tags = TaggableManager()

    def __str__(self):
        return self.title

    '''
    By overriding the save method we can execute custom logic before the
    object is stored in the database. The slugify function converts a string to
    a URL slug (“My blog title” string becomes “my-blog-title”). We have to call
    super().save(*args, **kwargs) to execute the default saving behavior
    and store the object in the database.
    '''
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


    '''
    The get_absolute_url method tells Django how to calculate the canonical
    URLforanobject. The reverse method returns a path reference that matches
    the view name and parameters.
    '''
    def get_absolute_url(self):
        return reverse(
            'blog:detail', args=[str(self.slug)]
        )

apps/blog/forms.py
# apps/blog/forms.py

# Django modules
from django.forms import ModelForm

# My modules
from blog.models import Post 

# Create your forms here.

class CreatePostForm(ModelForm):

	class Meta:
		model = Post
		fields = ['title','body','slug','tags','image']


class DeletePostForm(ModelForm):

	class Meta:
		model = Post
		fields = []

apps/blog/views.py
# apps/blog/views.py

# Django modules
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import permission_required
from django.core.paginator import Paginator

# Third party module
from taggit.models import Tag

# My modules
from blog.models import Post 
from blog.forms import CreatePostForm

# Create your views here.

def home_view(request, tag=None):
    tag_obj = None

    if not tag:
        posts = Post.objects.all()

    else:
        tag_obj = get_object_or_404(Tag, slug=tag)
        posts = Post.objects.filter(tags__in=[tag_obj])

    # Pagination
    '''
    The Paginator class allows us to split a QuerySet into parts. Pass in the
     objects you want paginate and the number of items you would like to have
     on each page.
    '''
    paginator = Paginator(posts, 1)
    '''
    We use request.GET.get('page') to get the current page
    number. The page parameter is assigned using a Query string (?page=1). 
    '''
    page = request.GET.get('page')
    '''
    The posts = paginator.get_page(page) line makes the page items 
    available through the posts object.
    '''
    posts = paginator.get_page(page)

    data = {
        'section':'home',
        'posts':posts,
        'tag': tag_obj,
    }

    return render(request, 'blog/home.html', data)


def post_detail_view(request, slug=None):
    post = get_object_or_404(Post, slug=slug)
    data = {
        'section':'Post detail',
        'post':post,
    }
    return render(request, 'blog/detail.html', data)


@permission_required('blog.create', raise_exception=True)
def post_create_view(request):

    # Handling POST request
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:home')

    # Handling GET request
    else:
        form = CreatePostForm()

    data = {
        'title':'Add new post',
        'section':'blog_create',
        'form':form,
    }

    return render(request, 'blog/create.html', data)


@permission_required('blog.edit', raise_exception=True)
def post_edit_view(request, pk=None):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES ,instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:detail', slug=post.slug)

    else:
        form = CreatePostForm(instance=post)

    data = {
        'title':'Edit post',
        'section':'blog_edit',
        'post':post,
        'form':form,
    }

    return render(request, 'blog/edit.html', data)


@permission_required('blog.delete', raise_exception=True)
def post_delete_view(request, pk=None):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CreatePostForm(request.POST, instance=post)
        if form.is_valid():
            post.delete()
            return redirect('blog:home')

    else:
        form = CreatePostForm(instance=post)

    data = {
        'title':'Delete post',
        'section':'blog_delete',
        'post':post,
        'form':form,
    }

    return render(request, 'blog/delete.html', data)


def about_view(request):
    data = {'section':'about'}
    return render(request, 'blog/about.html', data)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Blog Platform :: {% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
</head>
<body>
	<ul class="menu">
		<li>
			<a class="{% if section == 'home' %} active {% endif %}" href="{% url 'blog:home' %}">
				Home
			</a>
		</li>
		<li>
			<a class="{% if section == 'about' %} active {% endif %}" href="{% url 'blog:about' %}">
				About
			</a>
		</li>
		
		{% if perms.blog.add_post %}
		<li>
			<a class="{% if section == 'blog_create' %} active {% endif %}" href="{% url 'blog:create' %}">
				Add new post
			</a>
		</li>
		{% endif %}
		
		<li>
			{% if not user.is_authenticated %}
				<a href="{% url 'account_login' %}">Sign in</a>
			{% else %}
				<a href="{% url 'account_logout' %}">Sign out</a>
			{% endif %}
		</li>
	</ul>

	<hr>

	{% block content %}
	{% endblock content %}

	{% include 'inc/_post_list.html' with heading='Latest posts' %}

</body>
</html>

templates/blog/about.html
<!-- templates/blog/about.html -->

{% extends 'base.html' %}
{% block title %} {{ block.super }} {{ section }} {% endblock title %}

{% block content %}

	<div class="content">
		<h2>About page</h2>
		<p>This page using dynamic page title ...</p>
	</div>

{% endblock content %}

templates/blog/create.html
<!-- templates/blog/create.html -->

 {% extends "base.html" %}
 {% block title %} {{ block.super }} {{ title }} {% endblock title %}

 {% block content %}

 	<h1>{{ title }}</h1>

	<form action="{% url 'blog:create' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="button" type="submit">Create</button>
	</form>
 {% endblock content %}

templates/blog/delete.html
<!-- templates/blog/delete.html -->

 {% extends "base.html" %}
 {% block title %} {{ block.super }} {{ title }} {% endblock title %}

 {% block content %}

 	<h1>{{ title }}</h1>

	<form action="{% url 'blog:delete' post.pk %}" method="post">
		{% csrf_token %}
		{{ form }}

		Are you sure you want to delete this item:
		<br>
		
		<a href="{% url 'blog:detail' post.slug %}">
			({{ post.pk }}) {{ post.title }}
		</a>?
		<br>

		<button class="button" type="submit">Delete</button>
		<a href="{% url 'blog:home' %}">Cancel</a>
	</form>
	
 {% endblock content %}

templates/blog/detail.html
<!-- templates/blog/detail.html -->

{% extends 'base.html' %}
{% block title %} {{ block.super }} {{ post }} {% endblock title %}

{% block content %}

	<h2>{{ post.title }}
		[<a href="{% url 'blog:edit' pk=post.pk %}">Edit</a>]
	</h2>
	<p>
		Posted: {{ post.date|date:"M j, Y"}}
		{% if post.author %}
		by {{ post.author|title }}
		{% endif %}
	</p>

	<!-- Images -->
	<!-- 	{% if post.image %}
		<img class="post-img" src="{{ post.image.url }}" height="100">
	{% endif %} -->

	<!-- Image thumbnail -->
	{% if post.image %}
		<img class="post-img" src="{{ post.image_thumbnail.url }}">
	{% endif %}
	<p>{{ post.body }}</p>

	{% if post.tags %}
	<div class="tags">
		{% for tag in post.tags.all %}
		<a href="{% url 'blog:posts_by_tag' tag.slug %}">{{ tag }}</a>
		{% endfor %}
	</div>
	{% endif %}
	
{% endblock content %}

templates/blog/edit.html
<!-- templates/blog/edit.html -->

 {% extends "base.html" %}
 {% block title %} {{ block.super }} {{ title }} {% endblock title %}

 {% block content %}

 	<h1>{{ title }}</h1>

	<form action="{% url 'blog:edit' post.pk %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="button" type="submit">Update</button>
	</form>
	
 {% endblock content %}

templates/blog/home.html
<!-- templates/blog/home.html -->

{% extends 'base.html' %}
{% block title %} {{ block.super }} Home {% endblock title %}

{% block content %}

 <!-- here-->
 <!-- <p>{{ perms.blog }}</p> -->

	<div class="content">
		{% for post in posts %}
			<h2>
				<a href="{{ post.get_absolute_url }}">
					{{ post.title }}
				</a>
				<!-- [<a href="{% url 'blog:edit' pk=post.pk %}">Edit</a>]
				[<a href="{% url 'blog:delete' pk=post.pk %}">Delete</a>] -->
				<!-- Checking permissions as staff -->
				{% if perms.blog.change_post %}
					[<a href="{% url 'blog:edit' pk=post.pk %}">Edit</a>]
				{% endif %}
				<!-- Checking permissions as staff-->
				{% if perms.blog.delete_post %}
					[<a href="{% url 'blog:delete' pk=post.pk %}">Delete</a>]
				{% endif %}
			</h2>
			<p>
				Posted: {{ post.date|date:"M j, Y"}}
				{% if post.author %}
				by {{ post.author|title }}
				{% endif %}
			</p>
			<p>{{ post.pk }} : {{ post.body|truncatewords:15 }}</p>
		{% endfor %}
	</div>
	<div>
		{% if tag %}
			<p>Posts tagged with <strong>"{{ tag.name }}"</strong></p>
		{% endif %}
	</div>
	
	{% include 'inc/_pagination.html' with items=posts %}
	<!-- 
	The include template tag is used to “include” the _pagination.html
	template within the home.html template. We pass in the posts object (and the pagination data with it) using the items=posts keyword argument.
	 -->
{% endblock content %}

templates/inc/_pagination.html
<div class="pagination">
	{% if posts.has_previous %}
		<a href="?page=1">First</a>
		<a href="?page={{ posts.previous_page_number }}">Previous</a>
	{% endif %}
		<span>{{ posts.number }}</span>
		<span>of</span>
		<span>{{ posts.paginator.num_pages }}</span>
	{% if posts.has_next %}
		<a href="?page={{ posts.next_page_number }}">Next</a>
		<a href="?page={{ posts.paginator.num_pages }}">Last</a>
	{% endif %}
</div>

<!-- 
The posts object works the same as before for listing items but we also have some extra functionality available. These are the variables we use in the _pagination.html template file:

• posts.has_previous is True when there are previous pages.
• posts.previous_page_number stores the previous page number.
• posts.number stores the current page number.
• posts.paginator.num_pages stores the total number of pages.
• posts.has_next is True when there are more pages to browse after the
current page.
• posts.next_page_number stores the number for the next page.
-->

templates/inc/_post_list.html
<div class="post-list">

	<h2 class="post-list-heading">{{ heading }}</h2>

	{% for post in latest_posts %}
		<a href="{{ post.get_absolute_url }}" class="post-list-link {% cycle 'odd' 'even' %}">
			<div class="post-list-date">{{ post.date|date:"M j, Y" }}</div>
			<div class="post-list-title">{{ post.title|truncatechars:20 }}</div>
		</a>
	{% endfor %}
	
</div>